# -*- coding: utf-8 -*-
"""final_publish

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nusrgp7gKB6Eq5lw0E0H3WfSAZS4kM3F
"""

#!/usr/bin/env python3
import rospy
from std_msgs.msg import Int64
def talker():
    pub = rospy.Publisher('Test', Int64, queue_size=10)
    rospy.init_node('std_id', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        hello_str = 6352500587
        rospy.loginfo(hello_str)
        pub.publish(hello_str)
        rate.sleep()
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass