# -*- coding: utf-8 -*-
"""final_subscriber

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16voc6XQS14SisVHtrotYftFeGl6RjkeI
"""

#!/usr/bin/env python3

import rospy
from std_msgs.msg import Int64
def callback(data):
  rospy.loginfo(data)
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)
def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("std_id", Int64, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()