# -*- coding: utf-8 -*-
"""sort_object

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEmru4QDAsW4T7RzmQyPdtkW_h61VsAZ
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse':
[200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}

sort=sorted(obj_detected.items(), key=lambda x:x[1])
print(sort)